import fs from "node:fs";
import assert from "node:assert/strict";

const html = fs.readFileSync("index.html", "utf8");
const js = fs.readFileSync("app.js", "utf8");
const css = fs.readFileSync("styles.css", "utf8");
const sql = fs.readFileSync("supabase.sql", "utf8");
const vercel = fs.readFileSync("vercel.json", "utf8");

assert.match(html, /Oportunidades Próximas/);
assert.match(html, /dashboardView/);
assert.match(html, /wizardView/);
assert.match(html, /historyView/);
assert.doesNotMatch(html, /consumerAppView/);
assert.doesNotMatch(html, /consumerView/);
assert.doesNotMatch(html, /data-route="consumer"/);
assert.doesNotMatch(html, /currentPlaceSelect/);
assert.match(html, /loggedEmailBadge/);
assert.match(html, /userAvatar/);
assert.doesNotMatch(html, /João Silva/);
assert.doesNotMatch(html, /data-route="moderation"/);

assert.match(js, /ANDROID_AUTO_ENABLED = Boolean\(config\.androidAutoEnabled\)/);
assert.match(js, /androidAutoPoiPublished: false/);
assert.match(js, /mainStatus: "in_review"/);
assert.match(js, /validateLink/);
assert.match(js, /draft\.validUntil < draft\.validFrom/);
assert.doesNotMatch(js, /matchingConsumerAlerts/);
assert.doesNotMatch(js, /renderConsumer/);
assert.doesNotMatch(js, /consumerPreferences/);
assert.doesNotMatch(js, /save-opportunity/);
assert.match(js, /sidebar-collapsed/);
assert.match(js, /dashboardPlaceSelect/);
assert.match(js, /select-dashboard-place/);
assert.match(js, /googleBusinessProfile/);
assert.match(js, /connect-google-business/);
assert.match(js, /simulate-no-business-profile/);
assert.match(js, /select-google-location/);
assert.match(js, /Google Business Profile/);
assert.match(js, /startGoogleOAuth/);
assert.match(js, /handleGoogleOAuthCallback/);
assert.match(js, /response_type: "token id_token"/);
assert.match(js, /decodeJwtPayload/);
assert.match(js, /profile\.picture/);
assert.match(js, /https:\/\/www\.googleapis\.com\/auth\/business\.manage/);
assert.match(js, /oauth_code_received/);
assert.match(js, /oauth_profile_received/);
assert.match(js, /state\.route = "dashboard"/);
assert.match(js, /currentUserName/);
assert.match(js, /knownUserEmail/);
assert.match(js, /Conta Google autenticada/);
assert.match(js, /if \(loadedState\.userProfile\.email === LEGACY_DEFAULT_EMAIL\) loadedState\.userProfile\.email = ""/);
assert.match(js, /localStorage\.removeItem\(STORAGE_KEY\)/);
assert.match(js, /establishmentCategories/);
assert.match(js, /benefitSuggestions/);
assert.match(js, /Frete grátis para compras acima de R\$ 100/);
assert.match(js, /Compre hoje e retire em até 30 minutos/);
assert.match(js, /Brinde especial nas primeiras 20 compras/);
assert.match(js, /Descreva o Benefício\/Promoção/);
assert.match(js, /aprovação da IA Gemini/);
assert.match(js, /apply-benefit-suggestion/);
assert.match(js, /geminiReviewBenefitText/);
assert.match(js, /Bloqueado pela revisão Gemini/);
assert.match(js, /Android Auto/);
assert.match(js, /Classificação/);
assert.match(js, /7\. Revise e finalize seu Alerta/);
assert.match(js, /Math\.min\(7/);
assert.doesNotMatch(js, /function stepPreview/);
assert.doesNotMatch(js, /"Preview", "Revis/);
assert.match(js, /stock_clearance/);
assert.match(js, /Até zerar o estoque/);
assert.match(js, /categoryIdForClassification/);
assert.doesNotMatch(js, /function stepCategories/);
assert.doesNotMatch(js, /data-action="toggle-category"/);
assert.doesNotMatch(js, /data-action="select-primary-category"/);
assert.match(js, /editingPlaceName/);
assert.match(js, /editingPlaceAddress/);
assert.match(js, /editingPlaceNeighborhood/);
assert.match(js, /editingPlaceWebsite/);
assert.match(js, /editingPlaceLatitude/);
assert.match(js, /editingPlaceBindingStatus/);
assert.match(js, /save-place/);
assert.match(js, /edit-place/);
assert.match(js, /hasDefinedEstablishmentCategory/);
assert.match(js, /alertCategoryIdForPlace/);
assert.match(js, /renderHistory/);
assert.match(js, /addHistory/);
assert.match(js, /Condições para integração real/);
assert.doesNotMatch(js, /function renderWizardSummary/);
assert.doesNotMatch(js, /function renderModeration/);
assert.doesNotMatch(js, /approve-alert/);

assert.match(css, /app-shell/);
assert.match(css, /\[hidden\]\s*\{\s*display:\s*none\s*!important;\s*\}/);
assert.match(css, /wizard-shell/);
assert.doesNotMatch(css, /side-summary/);
assert.doesNotMatch(css, /consumer-shell/);
assert.doesNotMatch(css, /consumer-app-shell/);
assert.doesNotMatch(css, /opportunity-card/);
assert.match(css, /sidebar-collapsed/);
assert.match(css, /overflow-wrap: anywhere/);
assert.match(css, /badge\.muted/);
assert.match(css, /user-avatar/);
assert.match(css, /form-control/);
assert.match(css, /checkbox-stack/);
assert.match(css, /suggestion-chip/);
assert.match(css, /input\[type="checkbox"\]/);
assert.match(css, /benefit-textarea/);
assert.match(css, /choice-icon/);
assert.match(css, /centered-choice/);
assert.match(css, /gemini-review/);
assert.match(css, /repeat\(7, 1fr\)/);
assert.match(css, /max-width:\s*1180px/);
assert.match(css, /border-color:\s*var\(--green\)/);
assert.match(css, /0 16px 32px rgba\(11, 92, 255, 0\.28\)/);

assert.match(sql, /benefit_alerts/);
assert.match(sql, /android_auto_poi_published = false/);
assert.match(sql, /consumer_no_background_location/);
assert.match(sql, /opportunity_history/);
assert.match(vercel, /\/auth\/callback/);

console.log("static-checks ok");
